#from lightning_datamodules.base_supervised_datamodule import BaseSupervisedDatamodule
#from lightning_datamodules.base_semisup_datamodule import BaseSemisupDatamodule
#from lightning_datamodules.miniworld_v2 import MiniworldDmV2, MiniworldDmV2Semisup
#from lightning_datamodules.miniworld_v3 import MiniworldDmV3, MiniworldDmV3Semisup
#from lightning_datamodules.phr_pan_dm import PhrPanDm, PhrPanDmSemisup
#from lightning_datamodules.phr_pan_ndvi_dm import PhrPanNdviDm, PhrPanNdviDmSemisup
from .semcity_bdsd_dm import SemcityBdsdDm
from .digitanie_dm import DigitanieDm, DigitanieSemisupDm
