from pl_datamodules.base_supervised_datamodule import BaseSupervisedDatamodule
from pl_datamodules.base_semisup_datamodule import BaseSemisupDatamodule
# from pl_datamodules.isprs_vai_sup import IsprsVaiSup
from pl_datamodules.miniworld_sup import MiniworldSup
# from pl_datamodules.airs_sup import AirsSup
from pl_datamodules.miniworld_semisup import MiniworldSemisup