from pl_datamodules.base_class_supervised import BaseClassSupervised
from pl_datamodules.base_class_semisupervised import BaseClassSemisupervised
# from pl_datamodules.rot_equivariance_isprs_vaihingen import RotEquivarianceIsprsVaihingen
from pl_datamodules.isprs_vai_sup import IsprsVaiSup
from pl_datamodules.isprs_vai_semisup import IsprsVaiSemisup