from pl_datamodules.base_supervised_datamodule import BaseSupervisedDatamodule
from pl_datamodules.base_semisup_datamodule import BaseSemisupDatamodule
from pl_datamodules.miniworld.miniworld_v1 import MiniworldV1, MiniworldV1Semisup
from pl_datamodules.miniworld.miniworld_v2 import MiniworldV2, MiniworldV2Semisup
from pl_datamodules.miniworld.miniworld_v3 import MiniworldV3, MiniworldV3Semisup